version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: npm
    directories:
      - './api'
      - './'
      - './web'
      - './admin'
    schedule:
      interval: daily
      time: '00:00'
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - Ready to merge
    commit-message:
      prefix: bump
      include: scope

  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
      time: '00:00'
    open-pull-requests-limit: 2
    labels:
      - Ready to merge

    commit-message:
      prefix: bump
      include: scope

  # Fetch and update latest 'docker' packages
  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: daily
      time: '00:00'
    open-pull-requests-limit: 2
    labels:
      - Ready to merge

    commit-message:
      prefix: bump
      include: scope

  # Fetch and update latest 'docker-compose' packages
  - package-ecosystem: docker-compose
    directory: '/'
    schedule:
      interval: daily
      time: '00:00'
    open-pull-requests-limit: 2
    labels:
      - Ready to merge

    commit-message:
      prefix: bump
      include: scope
