services:
  postgres:
    image: postgres:18.1-alpine
    container_name: kompagnon-postgres
    ports:
      - '${DATABASE_PORT:-5432}:5432'
    env_file:
      - ./api/.env
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
