name: commits check

on:
  pull_request:
  merge_group:

jobs:
  block-autosquash-commits:
    runs-on: ubuntu-latest
    # Run only if not merge queue
    if: github.event_name != 'merge_group'
    permissions:
      pull-requests: read
    steps:
      - name: Block Autosquash Commits
        uses: xt0rted/block-autosquash-commits-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
